apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.fullName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.selectorLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.selectorLabel }}
    spec:
      containers:
        - name:  {{ .Values.containers.router.name}}
          image:  {{ .Values.containers.router.image}}
          env:
            - name: zmq.SocketUrl
              value: "tcp://*:{{ .Values.containers.router.zmqPort }}"

